name: Push and build
on:
    push:
        branches: ['main']
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@3
          with:
            node-version: 20
        - run: npm install
        - run: npm run build
