name: A simple demo workflow
on:
    push:
        branches: ['main']
jobs:
    demo-job:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: check nodejs version
              run: node --version

            - name: check npm version
              run: npm --version
